name: Deploy and test the model

on:
  workflow_dispatch:
    inputs:
      resource_group:
        description: 'Resource group name'
        required: true
        default: 'rg-dev-mlops' 
        type: string
      aml_workspace:
        description: 'Azure Machine Learning workspace name'
        required: true
        default: 'mlw-dev-mlops' 
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Set default aml workspace
      run: |
        az configure --defaults group="rg-dev-mlops"
        az configure --defaults workspace="mlw-dev-mlops"
    - name: Create endpoint and deploy
      run: |
        az ml model create --name "diabetes-model" \
                    --type "mlflow_model" \
                    --path "Azureml://jobs/$JOB_NAME/outputs/artifacts/model"
                    
        az ml online deployment create --name diabetes-deployment --endpoint my-endpoint -f deployment.yaml --all-traffic        
        
        
        
