name: Train in dev and run in prod environments

on:
  workflow_dispatch:
    inputs:
      resource_group:
        description: 'Resource group name'
        required: true
        default: 'rg-dev-mlops' 
        type: string
      aml_workspace:
        description: 'Azure Machine Learning workspace name'
        required: true
        default: 'mlw-dev-mlops' 
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Set default aml workspace
      run: |
        az configure --defaults group="rg-dev-mlops"
        az configure --defaults workspace="mlw-dev-mlops"
    - name: Create Azure Machine Learning workspace
      run: |
        az ml job create --file ./src/job.yml
  build:
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Set default aml workspace
      run: |
        az configure --defaults group="rg-dev-mlops"
        az configure --defaults workspace="mlw-dev-mlops"
    - name: Create Azure Machine Learning workspace
      run: |
        az ml job create --file ./src/job.yml
    - name: Get List of Registered Models
      run: |
        az ml model list
  
